// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Catalogservice service

type CatalogserviceService interface {
	FindItems(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error)
	RemoveItem(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	ListItems(ctx context.Context, in *ListSpecification, opts ...client.CallOption) (*Response, error)
}

type catalogserviceService struct {
	c    client.Client
	name string
}

func NewCatalogserviceService(name string, c client.Client) CatalogserviceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "catalog"
	}
	return &catalogserviceService{
		c:    c,
		name: name,
	}
}

func (c *catalogserviceService) FindItems(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Catalogservice.FindItems", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogserviceService) Create(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Catalogservice.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogserviceService) RemoveItem(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Catalogservice.RemoveItem", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogserviceService) ListItems(ctx context.Context, in *ListSpecification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Catalogservice.ListItems", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalogservice service

type CatalogserviceHandler interface {
	FindItems(context.Context, *Specification, *Response) error
	Create(context.Context, *Item, *Response) error
	RemoveItem(context.Context, *Specification, *Response) error
	ListItems(context.Context, *ListSpecification, *Response) error
}

func RegisterCatalogserviceHandler(s server.Server, hdlr CatalogserviceHandler, opts ...server.HandlerOption) error {
	type catalogservice interface {
		FindItems(ctx context.Context, in *Specification, out *Response) error
		Create(ctx context.Context, in *Item, out *Response) error
		RemoveItem(ctx context.Context, in *Specification, out *Response) error
		ListItems(ctx context.Context, in *ListSpecification, out *Response) error
	}
	type Catalogservice struct {
		catalogservice
	}
	h := &catalogserviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Catalogservice{h}, opts...))
}

type catalogserviceHandler struct {
	CatalogserviceHandler
}

func (h *catalogserviceHandler) FindItems(ctx context.Context, in *Specification, out *Response) error {
	return h.CatalogserviceHandler.FindItems(ctx, in, out)
}

func (h *catalogserviceHandler) Create(ctx context.Context, in *Item, out *Response) error {
	return h.CatalogserviceHandler.Create(ctx, in, out)
}

func (h *catalogserviceHandler) RemoveItem(ctx context.Context, in *Specification, out *Response) error {
	return h.CatalogserviceHandler.RemoveItem(ctx, in, out)
}

func (h *catalogserviceHandler) ListItems(ctx context.Context, in *ListSpecification, out *Response) error {
	return h.CatalogserviceHandler.ListItems(ctx, in, out)
}
