// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId             string   `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Champions            []string `protobuf:"bytes,3,rep,name=champions,proto3" json:"champions,omitempty"`
	BlueEssence          int32    `protobuf:"varint,4,opt,name=blue_essence,json=blueEssence,proto3" json:"blue_essence,omitempty"`
	RiotPoints           int32    `protobuf:"varint,5,opt,name=riot_points,json=riotPoints,proto3" json:"riot_points,omitempty"`
	Solo                 int32    `protobuf:"varint,6,opt,name=solo,proto3" json:"solo,omitempty"`
	Flex                 int32    `protobuf:"varint,7,opt,name=flex,proto3" json:"flex,omitempty"`
	PriceDollars         int32    `protobuf:"varint,8,opt,name=price_dollars,json=priceDollars,proto3" json:"price_dollars,omitempty"`
	PriceCents           int32    `protobuf:"varint,9,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Level                int32    `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	Login                string   `protobuf:"bytes,13,opt,name=login,proto3" json:"login,omitempty"`
	LoginPassword        string   `protobuf:"bytes,14,opt,name=login_password,json=loginPassword,proto3" json:"login_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Item) GetChampions() []string {
	if m != nil {
		return m.Champions
	}
	return nil
}

func (m *Item) GetBlueEssence() int32 {
	if m != nil {
		return m.BlueEssence
	}
	return 0
}

func (m *Item) GetRiotPoints() int32 {
	if m != nil {
		return m.RiotPoints
	}
	return 0
}

func (m *Item) GetSolo() int32 {
	if m != nil {
		return m.Solo
	}
	return 0
}

func (m *Item) GetFlex() int32 {
	if m != nil {
		return m.Flex
	}
	return 0
}

func (m *Item) GetPriceDollars() int32 {
	if m != nil {
		return m.PriceDollars
	}
	return 0
}

func (m *Item) GetPriceCents() int32 {
	if m != nil {
		return m.PriceCents
	}
	return 0
}

func (m *Item) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Item) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Item) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Item) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Item) GetLoginPassword() string {
	if m != nil {
		return m.LoginPassword
	}
	return ""
}

type Specification struct {
	Solo                 int32    `protobuf:"varint,1,opt,name=solo,proto3" json:"solo,omitempty"`
	Flex                 int32    `protobuf:"varint,2,opt,name=flex,proto3" json:"flex,omitempty"`
	PriceDollars         int32    `protobuf:"varint,3,opt,name=price_dollars,json=priceDollars,proto3" json:"price_dollars,omitempty"`
	PriceCents           int32    `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	ItemId               string   `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	VendorId             string   `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	PageNum              int32    `protobuf:"varint,7,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Item                 *Item    `protobuf:"bytes,8,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetSolo() int32 {
	if m != nil {
		return m.Solo
	}
	return 0
}

func (m *Specification) GetFlex() int32 {
	if m != nil {
		return m.Flex
	}
	return 0
}

func (m *Specification) GetPriceDollars() int32 {
	if m != nil {
		return m.PriceDollars
	}
	return 0
}

func (m *Specification) GetPriceCents() int32 {
	if m != nil {
		return m.PriceCents
	}
	return 0
}

func (m *Specification) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *Specification) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Specification) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Specification) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type Response struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	VendorId             string   `protobuf:"bytes,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Response) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Response) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

type ListSpecification struct {
	Solo                 int32    `protobuf:"varint,1,opt,name=solo,proto3" json:"solo,omitempty"`
	Flex                 int32    `protobuf:"varint,2,opt,name=flex,proto3" json:"flex,omitempty"`
	PriceDollars         int32    `protobuf:"varint,3,opt,name=price_dollars,json=priceDollars,proto3" json:"price_dollars,omitempty"`
	PriceCents           int32    `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	ItemId               string   `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	VendorId             string   `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int32    `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSpecification) Reset()         { *m = ListSpecification{} }
func (m *ListSpecification) String() string { return proto.CompactTextString(m) }
func (*ListSpecification) ProtoMessage()    {}
func (*ListSpecification) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *ListSpecification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSpecification.Unmarshal(m, b)
}
func (m *ListSpecification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSpecification.Marshal(b, m, deterministic)
}
func (m *ListSpecification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSpecification.Merge(m, src)
}
func (m *ListSpecification) XXX_Size() int {
	return xxx_messageInfo_ListSpecification.Size(m)
}
func (m *ListSpecification) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSpecification.DiscardUnknown(m)
}

var xxx_messageInfo_ListSpecification proto.InternalMessageInfo

func (m *ListSpecification) GetSolo() int32 {
	if m != nil {
		return m.Solo
	}
	return 0
}

func (m *ListSpecification) GetFlex() int32 {
	if m != nil {
		return m.Flex
	}
	return 0
}

func (m *ListSpecification) GetPriceDollars() int32 {
	if m != nil {
		return m.PriceDollars
	}
	return 0
}

func (m *ListSpecification) GetPriceCents() int32 {
	if m != nil {
		return m.PriceCents
	}
	return 0
}

func (m *ListSpecification) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *ListSpecification) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *ListSpecification) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListSpecification) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "catalog.Item")
	proto.RegisterType((*Specification)(nil), "catalog.Specification")
	proto.RegisterType((*Response)(nil), "catalog.Response")
	proto.RegisterType((*ListSpecification)(nil), "catalog.ListSpecification")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0xcd, 0x67, 0x9b, 0xd3, 0xa6, 0xb0, 0x83, 0xe8, 0x58, 0x05, 0xbb, 0x59, 0x84, 0x5e,
	0xc8, 0x5e, 0xac, 0x37, 0x0a, 0xde, 0x55, 0x85, 0x82, 0xc8, 0x92, 0x7d, 0x80, 0x90, 0x4d, 0xce,
	0xd6, 0x81, 0x24, 0x13, 0x32, 0xd3, 0xea, 0x23, 0xf8, 0x9a, 0x3e, 0xc2, 0xbe, 0x81, 0xcc, 0x99,
	0x36, 0xd2, 0x0f, 0x15, 0x2f, 0xf7, 0xaa, 0xf3, 0xff, 0x9d, 0x33, 0x39, 0xa7, 0xff, 0x73, 0x18,
	0x88, 0x8b, 0x5c, 0xe7, 0x95, 0x5c, 0x5d, 0xb6, 0x9d, 0xd4, 0x92, 0x0d, 0xb6, 0x32, 0xf9, 0xe1,
	0x81, 0xbf, 0xd4, 0x58, 0xb3, 0x09, 0xb8, 0xa2, 0xe4, 0xce, 0xcc, 0x99, 0x47, 0xa9, 0x2b, 0x4a,
	0xf6, 0x1c, 0xa2, 0x0d, 0x36, 0xa5, 0xec, 0x32, 0x51, 0x72, 0x97, 0xf0, 0xd0, 0x82, 0x65, 0xc9,
	0x5e, 0x40, 0x54, 0x7c, 0xcd, 0xeb, 0x56, 0xc8, 0x46, 0x71, 0x6f, 0xe6, 0xcd, 0xa3, 0xf4, 0x37,
	0x60, 0xe7, 0x30, 0xbe, 0xad, 0xd6, 0x98, 0xa1, 0x52, 0xd8, 0x14, 0xc8, 0xfd, 0x99, 0x33, 0x0f,
	0xd2, 0x91, 0x61, 0x1f, 0x2d, 0x62, 0x2f, 0x61, 0xd4, 0x09, 0xa9, 0xb3, 0x56, 0x8a, 0x46, 0x2b,
	0x1e, 0x50, 0x06, 0x18, 0x74, 0x4d, 0x84, 0x31, 0xf0, 0x95, 0xac, 0x24, 0x0f, 0x29, 0x42, 0x67,
	0xc3, 0xee, 0x2a, 0xfc, 0xce, 0x07, 0x96, 0x99, 0x33, 0xbb, 0x80, 0xb8, 0xed, 0x44, 0x81, 0x59,
	0x29, 0xab, 0x2a, 0xef, 0x14, 0x1f, 0x52, 0x70, 0x4c, 0xf0, 0x83, 0x65, 0xa6, 0x9a, 0x4d, 0x2a,
	0xd0, 0x54, 0x8b, 0x6c, 0x35, 0x42, 0x0b, 0x43, 0xd8, 0x63, 0x08, 0x2a, 0xdc, 0x60, 0xc5, 0x81,
	0x42, 0x56, 0x18, 0x8a, 0x75, 0x2e, 0x2a, 0x3e, 0xa2, 0xbf, 0x6f, 0x05, 0x9b, 0xc2, 0xb0, 0xcd,
	0x95, 0xfa, 0x26, 0xbb, 0x92, 0x8f, 0xad, 0x2f, 0x3b, 0x4d, 0xdf, 0x91, 0x2b, 0xd1, 0xf0, 0xd8,
	0xde, 0x20, 0xc1, 0x5e, 0xc1, 0x84, 0x0e, 0x59, 0x7f, 0x6f, 0x42, 0xe1, 0x98, 0xe8, 0xf5, 0x16,
	0x26, 0xf7, 0x0e, 0xc4, 0x37, 0x2d, 0x16, 0xe2, 0x4e, 0x14, 0xb9, 0x16, 0xb2, 0xe9, 0x4d, 0x70,
	0x4e, 0x98, 0xe0, 0xfe, 0xcd, 0x04, 0xef, 0xdf, 0x26, 0xf8, 0x47, 0x26, 0x3c, 0x85, 0x81, 0xd0,
	0x58, 0x9b, 0x79, 0x07, 0xd4, 0x5f, 0x68, 0xe4, 0xf2, 0x60, 0x15, 0xc2, 0x83, 0x55, 0x78, 0x66,
	0xec, 0x58, 0x61, 0xd6, 0xac, 0xeb, 0xed, 0x60, 0x06, 0x46, 0x7f, 0x59, 0xd7, 0xec, 0x1c, 0x7c,
	0xf3, 0x05, 0x1a, 0xc9, 0xe8, 0x2a, 0xbe, 0xdc, 0xad, 0xa0, 0xd9, 0xb7, 0x94, 0x42, 0x89, 0x84,
	0x61, 0x8a, 0xaa, 0x95, 0x8d, 0xc2, 0x3e, 0xdd, 0xf9, 0x63, 0x3a, 0xbb, 0x80, 0xc0, 0xfc, 0x2a,
	0xee, 0xce, 0xbc, 0xe3, 0x1c, 0x1b, 0xdb, 0x6f, 0xd7, 0xdb, 0x6f, 0x37, 0xf9, 0xe9, 0xc0, 0xd9,
	0x67, 0xa1, 0xf4, 0xc3, 0x33, 0x9a, 0x81, 0x6f, 0x8c, 0xdd, 0x6d, 0xbf, 0x39, 0xd3, 0xbe, 0x89,
	0x5a, 0xe8, 0xed, 0xd6, 0x5b, 0x71, 0x75, 0xef, 0xc0, 0x64, 0x61, 0x8d, 0xb9, 0xc1, 0x6e, 0x23,
	0x0a, 0x64, 0x6f, 0x21, 0xfa, 0x24, 0x9a, 0x72, 0x49, 0x06, 0x3d, 0xe9, 0x6d, 0xdb, 0x73, 0x61,
	0x7a, 0xd6, 0xf3, 0xdd, 0x4c, 0x92, 0x47, 0xec, 0x35, 0x84, 0x8b, 0x0e, 0x73, 0x8d, 0x6c, 0xdf,
	0xed, 0xd3, 0xd9, 0xef, 0x00, 0x52, 0xac, 0xe5, 0x06, 0xe9, 0x4d, 0xf9, 0xaf, 0x42, 0xef, 0x21,
	0x32, 0x83, 0xb1, 0x2d, 0x4e, 0xfb, 0x8c, 0xa3, 0x61, 0x9d, 0xbc, 0x7d, 0x1b, 0xd2, 0xbb, 0xf6,
	0xe6, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x9e, 0x86, 0x35, 0xe8, 0x04, 0x00, 0x00,
}
