// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalogv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId             string   `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Champions            []string `protobuf:"bytes,3,rep,name=champions,proto3" json:"champions,omitempty"`
	BlueEssence          int32    `protobuf:"varint,4,opt,name=blue_essence,json=blueEssence,proto3" json:"blue_essence,omitempty"`
	RiotPoints           int32    `protobuf:"varint,5,opt,name=riot_points,json=riotPoints,proto3" json:"riot_points,omitempty"`
	Solo                 int32    `protobuf:"varint,6,opt,name=solo,proto3" json:"solo,omitempty"`
	Flex                 int32    `protobuf:"varint,7,opt,name=flex,proto3" json:"flex,omitempty"`
	PriceDollars         int32    `protobuf:"varint,8,opt,name=price_dollars,json=priceDollars,proto3" json:"price_dollars,omitempty"`
	PriceCents           int32    `protobuf:"varint,9,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Level                int32    `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,12,opt,name=password,proto3" json:"password,omitempty"`
	Login                string   `protobuf:"bytes,13,opt,name=login,proto3" json:"login,omitempty"`
	LoginPassword        string   `protobuf:"bytes,14,opt,name=login_password,json=loginPassword,proto3" json:"login_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Item) GetChampions() []string {
	if m != nil {
		return m.Champions
	}
	return nil
}

func (m *Item) GetBlueEssence() int32 {
	if m != nil {
		return m.BlueEssence
	}
	return 0
}

func (m *Item) GetRiotPoints() int32 {
	if m != nil {
		return m.RiotPoints
	}
	return 0
}

func (m *Item) GetSolo() int32 {
	if m != nil {
		return m.Solo
	}
	return 0
}

func (m *Item) GetFlex() int32 {
	if m != nil {
		return m.Flex
	}
	return 0
}

func (m *Item) GetPriceDollars() int32 {
	if m != nil {
		return m.PriceDollars
	}
	return 0
}

func (m *Item) GetPriceCents() int32 {
	if m != nil {
		return m.PriceCents
	}
	return 0
}

func (m *Item) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Item) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Item) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Item) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Item) GetLoginPassword() string {
	if m != nil {
		return m.LoginPassword
	}
	return ""
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RemoveRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (m *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(m, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RemoveRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RemoveResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Deleted              int64    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func (m *RemoveResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RemoveResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

type Specification struct {
	Solo                 int32    `protobuf:"varint,1,opt,name=solo,proto3" json:"solo,omitempty"`
	Flex                 int32    `protobuf:"varint,2,opt,name=flex,proto3" json:"flex,omitempty"`
	PriceDollars         int32    `protobuf:"varint,3,opt,name=price_dollars,json=priceDollars,proto3" json:"price_dollars,omitempty"`
	PriceCents           int32    `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	ItemId               string   `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	VendorId             string   `protobuf:"bytes,6,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	PageNum              int32    `protobuf:"varint,7,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Item                 *Item    `protobuf:"bytes,8,opt,name=item,proto3" json:"item,omitempty"`
	Api                  string   `protobuf:"bytes,9,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetSolo() int32 {
	if m != nil {
		return m.Solo
	}
	return 0
}

func (m *Specification) GetFlex() int32 {
	if m != nil {
		return m.Flex
	}
	return 0
}

func (m *Specification) GetPriceDollars() int32 {
	if m != nil {
		return m.PriceDollars
	}
	return 0
}

func (m *Specification) GetPriceCents() int32 {
	if m != nil {
		return m.PriceCents
	}
	return 0
}

func (m *Specification) GetItemId() string {
	if m != nil {
		return m.ItemId
	}
	return ""
}

func (m *Specification) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Specification) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *Specification) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Specification) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type Response struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *Response) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{7}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{8}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ListResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "catalogv1.Item")
	proto.RegisterType((*CreateRequest)(nil), "catalogv1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "catalogv1.CreateResponse")
	proto.RegisterType((*RemoveRequest)(nil), "catalogv1.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "catalogv1.RemoveResponse")
	proto.RegisterType((*Specification)(nil), "catalogv1.Specification")
	proto.RegisterType((*Response)(nil), "catalogv1.Response")
	proto.RegisterType((*ListRequest)(nil), "catalogv1.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "catalogv1.ListResponse")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 839 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x8f, 0xe3, 0x44,
	0x10, 0x95, 0xed, 0x7c, 0xb9, 0xf2, 0x31, 0xbb, 0x3d, 0x88, 0xe9, 0x09, 0x2b, 0x30, 0x5e, 0x56,
	0x8c, 0x22, 0x26, 0xde, 0x09, 0xcb, 0x65, 0xc4, 0x01, 0x18, 0x58, 0x34, 0x12, 0xa0, 0x95, 0x57,
	0xda, 0x03, 0x42, 0x8a, 0x1c, 0xbb, 0xc6, 0x69, 0xb0, 0xdd, 0xc6, 0xdd, 0xc9, 0x2c, 0x42, 0x5c,
	0x90, 0x90, 0x38, 0xc3, 0x8d, 0xff, 0xc3, 0x81, 0x33, 0x7f, 0x81, 0x5f, 0xc1, 0x09, 0x75, 0xb7,
	0x13, 0xe2, 0xf9, 0xe2, 0xc0, 0x29, 0x5d, 0xaf, 0xaa, 0x5e, 0x57, 0xea, 0xbd, 0x4e, 0x60, 0x18,
	0x47, 0x32, 0xca, 0x78, 0x3a, 0x2d, 0x2b, 0x2e, 0x39, 0x71, 0xeb, 0x70, 0x7d, 0x32, 0x7e, 0x90,
	0x72, 0x9e, 0x66, 0x18, 0x44, 0x25, 0x0b, 0xa2, 0xa2, 0xe0, 0x32, 0x92, 0x8c, 0x17, 0xc2, 0x14,
	0x8e, 0xdf, 0xd1, 0x1f, 0xf1, 0x71, 0x8a, 0xc5, 0xb1, 0xb8, 0x8c, 0xd2, 0x14, 0xab, 0x80, 0x97,
	0xba, 0xe2, 0x7a, 0xb5, 0xff, 0xb3, 0x03, 0xad, 0x73, 0x89, 0x39, 0x19, 0x81, 0xcd, 0x12, 0x6a,
	0x79, 0xd6, 0x91, 0x1b, 0xda, 0x2c, 0x21, 0xaf, 0x81, 0xbb, 0xc6, 0x22, 0xe1, 0xd5, 0x9c, 0x25,
	0xd4, 0xd6, 0x70, 0xcf, 0x00, 0xe7, 0x09, 0x79, 0x00, 0x6e, 0xbc, 0x8c, 0xf2, 0x52, 0x11, 0x51,
	0xc7, 0x73, 0x8e, 0xdc, 0xf0, 0x5f, 0x80, 0xbc, 0x09, 0x83, 0x45, 0xb6, 0xc2, 0x39, 0x0a, 0x81,
	0x45, 0x8c, 0xb4, 0xe5, 0x59, 0x47, 0xed, 0xb0, 0xaf, 0xb0, 0x4f, 0x0c, 0x44, 0xde, 0x80, 0x7e,
	0xc5, 0xb8, 0x9c, 0x97, 0x9c, 0x15, 0x52, 0xd0, 0xb6, 0xae, 0x00, 0x05, 0x3d, 0xd3, 0x08, 0x21,
	0xd0, 0x12, 0x3c, 0xe3, 0xb4, 0xa3, 0x33, 0xfa, 0xac, 0xb0, 0x8b, 0x0c, 0x5f, 0xd2, 0xae, 0xc1,
	0xd4, 0x99, 0x3c, 0x84, 0x61, 0x59, 0xb1, 0x18, 0xe7, 0x09, 0xcf, 0xb2, 0xa8, 0x12, 0xb4, 0xa7,
	0x93, 0x03, 0x0d, 0x7e, 0x6c, 0x30, 0x75, 0x9b, 0x29, 0x8a, 0x51, 0xdd, 0xe6, 0x9a, 0xdb, 0x34,
	0x74, 0xa6, 0x10, 0xf2, 0x0a, 0xb4, 0x33, 0x5c, 0x63, 0x46, 0x41, 0xa7, 0x4c, 0xa0, 0x50, 0xcc,
	0x23, 0x96, 0xd1, 0xbe, 0xfe, 0xfa, 0x26, 0x20, 0x63, 0xe8, 0x95, 0x91, 0x10, 0x97, 0xbc, 0x4a,
	0xe8, 0xc0, 0xec, 0x65, 0x13, 0x6b, 0x1e, 0x9e, 0xb2, 0x82, 0x0e, 0x4d, 0x87, 0x0e, 0xc8, 0x23,
	0x18, 0xe9, 0xc3, 0x7c, 0xdb, 0x37, 0xd2, 0xe9, 0xa1, 0x46, 0x9f, 0xd5, 0xa0, 0xff, 0x14, 0x86,
	0x67, 0x15, 0x46, 0x12, 0x43, 0xfc, 0x76, 0x85, 0x42, 0x92, 0x7b, 0xe0, 0x44, 0x25, 0xab, 0x35,
	0x51, 0x47, 0xf2, 0x10, 0x5a, 0x4c, 0x62, 0xae, 0xf5, 0xe8, 0xcf, 0xf6, 0xa6, 0x5b, 0x4f, 0x4c,
	0x95, 0x86, 0xa1, 0x4e, 0xfa, 0x33, 0x18, 0x6d, 0x78, 0x44, 0xc9, 0x0b, 0x81, 0x37, 0x10, 0x19,
	0xb5, 0x15, 0x8d, 0xa3, 0xd4, 0xf6, 0x4f, 0x60, 0x18, 0x62, 0xce, 0xd7, 0x77, 0xdc, 0x7d, 0xb5,
	0xe5, 0x7d, 0x18, 0x6d, 0x5a, 0x6e, 0xbd, 0x86, 0x42, 0x37, 0xc1, 0x0c, 0x25, 0x6e, 0x1a, 0x37,
	0xa1, 0xff, 0x93, 0x0d, 0xc3, 0xe7, 0x25, 0xc6, 0xec, 0x82, 0xc5, 0xda, 0x90, 0x5b, 0xc5, 0xad,
	0x1b, 0x14, 0xb7, 0xef, 0x52, 0xdc, 0xf9, 0x6f, 0xc5, 0x5b, 0xd7, 0x14, 0x3f, 0x80, 0xae, 0x5a,
	0x96, 0x32, 0x77, 0x5b, 0xcf, 0xdb, 0x51, 0xe1, 0xf9, 0x15, 0xdf, 0x77, 0xae, 0xf8, 0xfe, 0x50,
	0x69, 0x9f, 0xe2, 0xbc, 0x58, 0xe5, 0xb5, 0x0b, 0xbb, 0x2a, 0xfe, 0x62, 0x95, 0x6f, 0xa5, 0xe9,
	0xdd, 0x21, 0xcd, 0x66, 0x43, 0xee, 0x76, 0x43, 0xfe, 0x19, 0xf4, 0xee, 0xd8, 0xdf, 0x23, 0x68,
	0xab, 0x3e, 0x41, 0x6d, 0xcf, 0xb9, 0x89, 0xd5, 0x64, 0xfd, 0x73, 0xe8, 0x7f, 0xc6, 0x84, 0xbc,
	0x5d, 0x3b, 0x02, 0x2d, 0x35, 0x67, 0x2d, 0x82, 0x3e, 0x6b, 0xaf, 0xb2, 0x9c, 0x49, 0xbd, 0x3f,
	0x27, 0x34, 0x81, 0xff, 0x29, 0x0c, 0x0c, 0xd5, 0xff, 0x9c, 0x69, 0xf6, 0xb7, 0x0d, 0xa3, 0x33,
	0x93, 0x79, 0x8e, 0xd5, 0x9a, 0xc5, 0x48, 0xbe, 0x04, 0xf7, 0x29, 0x2b, 0x12, 0x55, 0x25, 0x08,
	0xdd, 0xe9, 0x6b, 0x18, 0x61, 0xbc, 0xbf, 0x93, 0xd9, 0xcc, 0xe1, 0xbf, 0xfe, 0xe3, 0x9f, 0x7f,
	0xfd, 0x6a, 0x53, 0x7f, 0x3f, 0x58, 0x9f, 0x04, 0x75, 0x5e, 0x04, 0x02, 0xa3, 0x2a, 0x5e, 0x9e,
	0x5a, 0x13, 0xf2, 0x02, 0x3a, 0xc6, 0xf4, 0x0d, 0xe2, 0xc6, 0x7b, 0x1a, 0x1f, 0xde, 0x90, 0xa9,
	0xe9, 0x0f, 0x34, 0xfd, 0x7d, 0x7f, 0xb0, 0x4b, 0xaf, 0x78, 0xbf, 0x02, 0x30, 0x2e, 0xd7, 0x3f,
	0x92, 0xb4, 0x31, 0xda, 0xce, 0x7b, 0x69, 0x70, 0x37, 0x9f, 0x85, 0x7f, 0xa8, 0xb9, 0xf7, 0x27,
	0xf7, 0x1b, 0xa3, 0x7f, 0xcf, 0x92, 0x1f, 0xc8, 0x0b, 0x70, 0xd5, 0xb6, 0xcd, 0x46, 0x5e, 0xdd,
	0xa1, 0xd8, 0x91, 0x73, 0x7c, 0x70, 0x0d, 0xaf, 0x89, 0xa9, 0x26, 0x26, 0xfe, 0xb0, 0x41, 0x7c,
	0x6a, 0x4d, 0x3e, 0xfa, 0xc3, 0xfa, 0xe5, 0xc3, 0xdf, 0x2d, 0x82, 0xb0, 0x57, 0x4b, 0xe0, 0x09,
	0xa3, 0x81, 0xff, 0x39, 0xec, 0xc5, 0x4d, 0x88, 0x4c, 0x96, 0x52, 0x96, 0xe2, 0x34, 0x08, 0x52,
	0x26, 0x97, 0xab, 0xc5, 0x34, 0xe6, 0x79, 0x10, 0x7f, 0xb3, 0x58, 0x44, 0x59, 0x16, 0x88, 0x7c,
	0x55, 0x5d, 0xb0, 0xe2, 0xb8, 0xee, 0x19, 0x8f, 0x16, 0x59, 0xb4, 0xfc, 0x60, 0x19, 0x95, 0xe5,
	0x77, 0x53, 0x5e, 0xa5, 0x33, 0xe7, 0x64, 0xfa, 0x78, 0x62, 0x59, 0xb3, 0x7b, 0x51, 0x59, 0x66,
	0xb5, 0x80, 0xc1, 0xd7, 0x82, 0x17, 0xa7, 0xd7, 0x90, 0xf0, 0x3d, 0x70, 0x9e, 0x3c, 0x7e, 0x42,
	0xa6, 0xf0, 0x56, 0x88, 0x72, 0x55, 0x15, 0x98, 0x78, 0x97, 0x4b, 0x2c, 0xbc, 0x0a, 0x05, 0x5f,
	0x55, 0x31, 0x7a, 0x09, 0x47, 0x51, 0xbc, 0x2d, 0x3d, 0x7c, 0xc9, 0x84, 0x24, 0x1d, 0x68, 0xfd,
	0x66, 0x5b, 0xdd, 0x45, 0x47, 0xff, 0x51, 0xbd, 0xfb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f,
	0x09, 0x6a, 0xd4, 0x10, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	FindItems(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	RemoveItem(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	ListItems(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) FindItems(ctx context.Context, in *Specification, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/catalogv1.CatalogService/FindItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/catalogv1.CatalogService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RemoveItem(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/catalogv1.CatalogService/RemoveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListItems(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/catalogv1.CatalogService/ListItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	FindItems(context.Context, *Specification) (*Response, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	RemoveItem(context.Context, *RemoveRequest) (*RemoveResponse, error)
	ListItems(context.Context, *ListRequest) (*ListResponse, error)
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_FindItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Specification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).FindItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogv1.CatalogService/FindItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).FindItems(ctx, req.(*Specification))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogv1.CatalogService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogv1.CatalogService/RemoveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RemoveItem(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catalogv1.CatalogService/ListItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListItems(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catalogv1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindItems",
			Handler:    _CatalogService_FindItems_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _CatalogService_Create_Handler,
		},
		{
			MethodName: "RemoveItem",
			Handler:    _CatalogService_RemoveItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _CatalogService_ListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
